//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRT.Astra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSRT.Astra.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your PSO2 installation directory.
        /// </summary>
        internal static string InstallSelectorWindow {
            get {
                return ResourceManager.GetString("InstallSelectorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string InstallSelectorWindow_Browse {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file browser to choose your PSO2 directory.
        /// </summary>
        internal static string InstallSelectorWindow_BrowseTooltip {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_BrowseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a PSO2 installation! Astra will update and launch the game from here..
        /// </summary>
        internal static string InstallSelectorWindow_InstallFoundHint {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_InstallFoundHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install PSO2.
        /// </summary>
        internal static string InstallSelectorWindow_InstallPSO2 {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_InstallPSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path invalid—the folder doesn&apos;t exist or the path is malformed..
        /// </summary>
        internal static string InstallSelectorWindow_InvalidDirectoryHint {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_InvalidDirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a PSO2 installation here. Astra will install PSO2 to this folder..
        /// </summary>
        internal static string InstallSelectorWindow_NoInstallFoundHint {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_NoInstallFoundHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your PSO2 installation directory..
        /// </summary>
        internal static string InstallSelectorWindow_PathEmptyHint {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_PathEmptyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your PSO2 install directory.
        /// </summary>
        internal static string InstallSelectorWindow_SelectInstallDirectory {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_SelectInstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string InstallSelectorWindow_Title {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Astra.
        /// </summary>
        internal static string InstallSelectorWindow_UpdatePSO2 {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_UpdatePSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArksLayer.
        /// </summary>
        internal static string Log_ArksLayer {
            get {
                return ResourceManager.GetString("Log_ArksLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astra Options.
        /// </summary>
        internal static string MainWindow_AstraOptions {
            get {
                return ResourceManager.GetString("MainWindow_AstraOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher tweaks for advanced users—tread carefully!.
        /// </summary>
        internal static string MainWindow_AstraOptionsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_AstraOptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Patch (ARKS Layer).
        /// </summary>
        internal static string MainWindow_EnglishPatchCheckbox {
            get {
                return ResourceManager.GetString("MainWindow_EnglishPatchCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads and enables ARKS Layer&apos;s translation tools—use this if you want to play PSO2 in English.
        /// </summary>
        internal static string MainWindow_EnglishPatchCheckboxTooltip {
            get {
                return ResourceManager.GetString("MainWindow_EnglishPatchCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch PSO2.
        /// </summary>
        internal static string MainWindow_LaunchPSO2 {
            get {
                return ResourceManager.GetString("MainWindow_LaunchPSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the game!.
        /// </summary>
        internal static string MainWindow_LaunchPSO2Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_LaunchPSO2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSO2 Options.
        /// </summary>
        internal static string MainWindow_PSO2Options {
            get {
                return ResourceManager.GetString("MainWindow_PSO2Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PSO2&apos;s graphics settings, including fullscreen mode and UI scale.
        /// </summary>
        internal static string MainWindow_PSO2OptionsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_PSO2OptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT Extended Features.
        /// </summary>
        internal static string MainWindow_PSRTCheckbox {
            get {
                return ResourceManager.GetString("MainWindow_PSRTCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables PSRT Core—some tools may need this to function.
        /// </summary>
        internal static string MainWindow_PSRTCheckboxTooltip {
            get {
                return ResourceManager.GetString("MainWindow_PSRTCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset GameGuard.
        /// </summary>
        internal static string MainWindow_ResetGameGuard {
            get {
                return ResourceManager.GetString("MainWindow_ResetGameGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces GameGuard files to be redownloaded the next time you launch PSO2—may resolve GameGuard errors.
        /// </summary>
        internal static string MainWindow_ResetGameGuardTooltip {
            get {
                return ResourceManager.GetString("MainWindow_ResetGameGuardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telepipe Proxy (ARKS Layer).
        /// </summary>
        internal static string MainWindow_TelepipeCheckbox {
            get {
                return ResourceManager.GetString("MainWindow_TelepipeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads and enables ARKS Layer&apos;s translation tools—use this if PSO2 is blocked in your country.
        /// </summary>
        internal static string MainWindow_TelepipeCheckboxTooltip {
            get {
                return ResourceManager.GetString("MainWindow_TelepipeCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to download!.
        /// </summary>
        internal static string MainWindow_UpdateAvailableDownload {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAvailableDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PSRT.Astra Version {0} is available..
        /// </summary>
        internal static string MainWindow_UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify (File Check).
        /// </summary>
        internal static string MainWindow_VerifyFiles {
            get {
                return ResourceManager.GetString("MainWindow_VerifyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redownloads missing or corrupt game files—may resolve various game issues.
        /// </summary>
        internal static string MainWindow_VerifyFilesTooltip {
            get {
                return ResourceManager.GetString("MainWindow_VerifyFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telepipe Config Url.
        /// </summary>
        internal static string OptionsWindow_TelepipeProxyUrl {
            get {
                return ResourceManager.GetString("OptionsWindow_TelepipeProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url override for custom Telepipe proxy json configuration file. Leaving this empty uses the default Telepipe configuration..
        /// </summary>
        internal static string OptionsWindow_TelepipeProxyUrlDescription {
            get {
                return ResourceManager.GetString("OptionsWindow_TelepipeProxyUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsWindow_Title {
            get {
                return ResourceManager.GetString("OptionsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Fullscreen.
        /// </summary>
        internal static string PSO2OptionsWindow_BorderlessFullscreen {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_BorderlessFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over an option for more information about its effects on your game..
        /// </summary>
        internal static string PSO2OptionsWindow_DefaultHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_DefaultHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard your changes?.
        /// </summary>
        internal static string PSO2OptionsWindow_DiscardChanges {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable DirectX 9Ex Features.
        /// </summary>
        internal static string PSO2OptionsWindow_EnableDirectX9Ex {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_EnableDirectX9Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets whether PSO2 will use newer DirectX features. Disabling this may fix graphics-related crashes on older systems, but will negatively impact performance and memory usage.
        ///
        ///If unsure, set this to Enabled..
        /// </summary>
        internal static string PSO2OptionsWindow_EnableDirectX9ExHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_EnableDirectX9ExHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Fullscreen.
        /// </summary>
        internal static string PSO2OptionsWindow_ExclusiveFullscreen {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_ExclusiveFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate Limit.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit120 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 144 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit144 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 240 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit240 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit30 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit60 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the maximum framerate PSO2 will run at. Setting this below your monitor&apos;s refresh rate (usually 60) will decrease visual smoothness, but may reduce hitching. Higher values will increase strain on your graphics card, but may make the game feel more responsive.
        ///
        ///If unsure, set this to 60 FPS..
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimitHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimitHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimitUnlimited {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimitUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Game Presets (Simple Render Setting).
        /// </summary>
        internal static string PSO2OptionsWindow_GraphicsPreset {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_GraphicsPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts your in-game graphics settings, overriding any changes. Higher values enable more eye-candy, but place more strain on your system. Some options may have no effect when Shader Quality is set to Low or Standard Quality..
        /// </summary>
        internal static string PSO2OptionsWindow_GraphicsPresetHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_GraphicsPresetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string PSO2OptionsWindow_Information {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_QualityHigh {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_QualityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_QualityLow {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_QualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_QualityStandard {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_QualityStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string PSO2OptionsWindow_Resolution {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets how many pixels the game renders each frame. This typically has the largest impact on performance and visual quality. Higher values place more strain on your graphics card. No effect when Window Mode is set to Borderless Fullscreen.
        ///
        ///If unsure, set this to your monitor&apos;s resolution..
        /// </summary>
        internal static string PSO2OptionsWindow_ResolutionHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_ResolutionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_ShaderQuality {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_ShaderQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the quality of in-game lighting and effects. Higher quality places more strain on your graphics card. Some in-game options will have no effect on Low or Standard Quality..
        /// </summary>
        internal static string PSO2OptionsWindow_ShaderQualityHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_ShaderQualityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_TextureQuality {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_TextureQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the resolution of in-game textures. Higher values will use sharper textures, but will also take up more graphics memory. This usually has negligible impact on performance, but a major impact on visual quality. Some low-end systems with weak or integrated graphics may need to lower this..
        /// </summary>
        internal static string PSO2OptionsWindow_TextureQualityHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_TextureQualityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Scale.
        /// </summary>
        internal static string PSO2OptionsWindow_UIScale {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.25x Scale.
        /// </summary>
        internal static string PSO2OptionsWindow_UIScale1Point25x {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScale1Point25x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5x Scale.
        /// </summary>
        internal static string PSO2OptionsWindow_UIScale1Point5x {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScale1Point5x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1x Scale.
        /// </summary>
        internal static string PSO2OptionsWindow_UIScale1x {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScale1x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the size of in-game interface elements, like your subpalette and HP bar. This option has no effect on performance..
        /// </summary>
        internal static string PSO2OptionsWindow_UIScaleHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScaleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        internal static string PSO2OptionsWindow_Windowed {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_Windowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Mode.
        /// </summary>
        internal static string PSO2OptionsWindow_WindowMode {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_WindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets whether the game fills your screen. Borderless Fullscreen and Windowed allow you to switch applications quickly, but add a very small amount of display latency on some systems. Exclusive Fullscreen responds slightly faster, but switching applications is slower and may crash.
        ///
        ///If unsure, set this to Borderless Fullscreen..
        /// </summary>
        internal static string PSO2OptionsWindow_WindowModeHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_WindowModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT Astra.
        /// </summary>
        internal static string PSRTAstra {
            get {
                return ResourceManager.GetString("PSRTAstra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
    }
}
