//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRT.Astra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSRT.Astra.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arks Layer.
        /// </summary>
        internal static string AboutWindow_ArksLayer {
            get {
                return ResourceManager.GetString("AboutWindow_ArksLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin framework and game translations (used with permission).
        /// </summary>
        internal static string AboutWindow_ArksLayerCredit {
            get {
                return ResourceManager.GetString("AboutWindow_ArksLayerCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⓒ 2019 George &quot;Yen&quot; Bott, in cooperation with all GitHub contributors. Distributed under the MIT license..
        /// </summary>
        internal static string AboutWindow_CopyrightInformation {
            get {
                return ResourceManager.GetString("AboutWindow_CopyrightInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        internal static string AboutWindow_Discord {
            get {
                return ResourceManager.GetString("AboutWindow_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PSRT community hub: chat with developers and get help with using Astra in real-time.
        /// </summary>
        internal static string AboutWindow_DiscordDescription {
            get {
                return ResourceManager.GetString("AboutWindow_DiscordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string AboutWindow_GitHub {
            get {
                return ResourceManager.GetString("AboutWindow_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Astra&apos;s development: read code and changelogs, request features, and report bugs.
        /// </summary>
        internal static string AboutWindow_GitHubDescription {
            get {
                return ResourceManager.GetString("AboutWindow_GitHubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSO-World.
        /// </summary>
        internal static string AboutWindow_PSOW {
            get {
                return ResourceManager.GetString("AboutWindow_PSOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request features and report bugs (responses may be slower).
        /// </summary>
        internal static string AboutWindow_PSOWDescription {
            get {
                return ResourceManager.GetString("AboutWindow_PSOWDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update Astra.
        ///If this is a repeat issue please click below to upload the error log information and share it with a developer.
        ///
        ///Would you like to upload the error information?.
        /// </summary>
        internal static string Astra_ErrorUpdating_WindowMessage {
            get {
                return ResourceManager.GetString("Astra_ErrorUpdating_WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of Astra is already running.
        /// </summary>
        internal static string Astra_InstanceAlreadyRunning_WindowMessage {
            get {
                return ResourceManager.GetString("Astra_InstanceAlreadyRunning_WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astra cannot ensure a valid PSO2 installation with an out of date client.
        ///
        ///Would you like to launch the current version of Astra anyway?.
        /// </summary>
        internal static string Astra_LaunchAnyway_WindowMessage {
            get {
                return ResourceManager.GetString("Astra_LaunchAnyway_WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for Astra is avaliable but the auto updater is unable to install it.
        ///Astra is unable to ensure a valid PSO2 installation with an out of date client.
        ///
        ///Would you like to open the latest Astra release page containing a manual download?.
        /// </summary>
        internal static string Astra_ManualUpdate_WindowMessage {
            get {
                return ResourceManager.GetString("Astra_ManualUpdate_WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT.Astra has a dedicated Discord for development, troubleshooting and general discussion. You can post the link to your error log here and get responses on how to solve your issue.
        ///Would you like to join this Discord server now?.
        /// </summary>
        internal static string Astra_OpenDiscord_WindowMessage {
            get {
                return ResourceManager.GetString("Astra_OpenDiscord_WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT.Astra Discord.
        /// </summary>
        internal static string Astra_OpenDiscord_WindowTitle {
            get {
                return ResourceManager.GetString("Astra_OpenDiscord_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT Astra has encountered an unrecoverable error.
        ///If this is a repeating issue, please click below to upload the error information and share it with a developer.
        ///Would you like to upload the error information?.
        /// </summary>
        internal static string Astra_UnhandledException_WindowMessage {
            get {
                return ResourceManager.GetString("Astra_UnhandledException_WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT Astra fatal exception.
        /// </summary>
        internal static string Astra_UnhandledException_WindowTitle {
            get {
                return ResourceManager.GetString("Astra_UnhandledException_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload log information..
        /// </summary>
        internal static string Astra_UploadLogError_WindowMessage {
            get {
                return ResourceManager.GetString("Astra_UploadLogError_WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading log.
        /// </summary>
        internal static string Astra_UploadLogError_WindowTitle {
            get {
                return ResourceManager.GetString("Astra_UploadLogError_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your PSO2 installation directory.
        /// </summary>
        internal static string InstallSelectorWindow {
            get {
                return ResourceManager.GetString("InstallSelectorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string InstallSelectorWindow_Browse {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file browser to choose your PSO2 directory.
        /// </summary>
        internal static string InstallSelectorWindow_BrowseTooltip {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_BrowseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running Astra on an existing installation of PSO2.
        ///
        ///The application will report it is updating all of your game files but do not worry, Astra is only scanning the files to learn about your PSO2 installation.
        ///Only downloads of corrupt/missing/outdated files occur.
        ///
        ///This operation will only happen to completion one time, after this the operation is near instant and ensures your PSO2 installation is always kept in a working state..
        /// </summary>
        internal static string InstallSelectorWindow_ExistingInstallationSelectMessage {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_ExistingInstallationSelectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a PSO2 installation! Astra will update and launch the game from here..
        /// </summary>
        internal static string InstallSelectorWindow_InstallFoundHint {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_InstallFoundHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install PSO2.
        /// </summary>
        internal static string InstallSelectorWindow_InstallPSO2 {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_InstallPSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path invalid—the folder doesn&apos;t exist or the path is malformed..
        /// </summary>
        internal static string InstallSelectorWindow_InvalidDirectoryHint {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_InvalidDirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a PSO2 installation here. Astra will install PSO2 to this folder..
        /// </summary>
        internal static string InstallSelectorWindow_NoInstallFoundHint {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_NoInstallFoundHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your PSO2 installation directory..
        /// </summary>
        internal static string InstallSelectorWindow_PathEmptyHint {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_PathEmptyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your PSO2 install directory.
        /// </summary>
        internal static string InstallSelectorWindow_SelectInstallDirectory {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_SelectInstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string InstallSelectorWindow_Title {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Astra.
        /// </summary>
        internal static string InstallSelectorWindow_UpdatePSO2 {
            get {
                return ResourceManager.GetString("InstallSelectorWindow_UpdatePSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Astra.
        /// </summary>
        internal static string MainWindow_AboutAstra {
            get {
                return ResourceManager.GetString("MainWindow_AboutAstra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits and contact information.
        /// </summary>
        internal static string MainWindow_AboutAstraTooltip {
            get {
                return ResourceManager.GetString("MainWindow_AboutAstraTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while verifying the Arks-Layer tools. The game should still launch, but translations and proxy functionality may not be updated, and may not work if they&apos;re out of date.
        ///
        ///Launch the game without verifying Arks-Layer tools?
        ///
        ///(If this issue happens consistently, please select &quot;No&quot; and file a report with the PSRT.Astra developers!).
        /// </summary>
        internal static string MainWindow_ArksLayerErrorMessage {
            get {
                return ResourceManager.GetString("MainWindow_ArksLayerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astra Options.
        /// </summary>
        internal static string MainWindow_AstraOptions {
            get {
                return ResourceManager.GetString("MainWindow_AstraOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher tweaks for advanced users—tread carefully!.
        /// </summary>
        internal static string MainWindow_AstraOptionsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_AstraOptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Patch (ARKS Layer).
        /// </summary>
        internal static string MainWindow_EnglishPatchCheckbox {
            get {
                return ResourceManager.GetString("MainWindow_EnglishPatchCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads and enables ARKS Layer&apos;s translation tools—use this if you want to play PSO2 in English.
        /// </summary>
        internal static string MainWindow_EnglishPatchCheckboxTooltip {
            get {
                return ResourceManager.GetString("MainWindow_EnglishPatchCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch PSO2.
        /// </summary>
        internal static string MainWindow_LaunchButton_Launch {
            get {
                return ResourceManager.GetString("MainWindow_LaunchButton_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the game!.
        /// </summary>
        internal static string MainWindow_LaunchButton_LaunchTooltip {
            get {
                return ResourceManager.GetString("MainWindow_LaunchButton_LaunchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for PSO2 to exit.
        /// </summary>
        internal static string MainWindow_LaunchButton_PSO2Running {
            get {
                return ResourceManager.GetString("MainWindow_LaunchButton_PSO2Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astra cannot make changes to PSO2 while the game is running.
        /// </summary>
        internal static string MainWindow_LaunchButton_PSO2RunningTooltip {
            get {
                return ResourceManager.GetString("MainWindow_LaunchButton_PSO2RunningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MainWindow_LaunchButton_Updating {
            get {
                return ResourceManager.GetString("MainWindow_LaunchButton_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Progress will be resumed next launch).
        /// </summary>
        internal static string MainWindow_LaunchButton_UpdatingSubText {
            get {
                return ResourceManager.GetString("MainWindow_LaunchButton_UpdatingSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astra is updating the game, canceling will not lose any update progress.
        /// </summary>
        internal static string MainWindow_LaunchButton_UpdatingTooltip {
            get {
                return ResourceManager.GetString("MainWindow_LaunchButton_UpdatingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom mod files.
        /// </summary>
        internal static string MainWindow_ModFilesCheckbox {
            get {
                return ResourceManager.GetString("MainWindow_ModFilesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy mod files from the pso2_bin/mods/ directory to ensure
        ///no corruption occurs with game updates.
        /// </summary>
        internal static string MainWindow_ModFilesCheckboxTooltip {
            get {
                return ResourceManager.GetString("MainWindow_ModFilesCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing files.
        /// </summary>
        internal static string MainWindow_Phase_Compare {
            get {
                return ResourceManager.GetString("MainWindow_Phase_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting censor file.
        /// </summary>
        internal static string MainWindow_Phase_DeleteCensorFile {
            get {
                return ResourceManager.GetString("MainWindow_Phase_DeleteCensorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading configuration file.
        /// </summary>
        internal static string MainWindow_Phase_DownloadConfiguration {
            get {
                return ResourceManager.GetString("MainWindow_Phase_DownloadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing English patch.
        /// </summary>
        internal static string MainWindow_Phase_EnglishPatch_TitleDisabled {
            get {
                return ResourceManager.GetString("MainWindow_Phase_EnglishPatch_TitleDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing English patch.
        /// </summary>
        internal static string MainWindow_Phase_EnglishPatch_TitleEnabled {
            get {
                return ResourceManager.GetString("MainWindow_Phase_EnglishPatch_TitleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing large address aware patch.
        /// </summary>
        internal static string MainWindow_Phase_LargeAddressAware {
            get {
                return ResourceManager.GetString("MainWindow_Phase_LargeAddressAware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Phantasy Star Online 2.
        /// </summary>
        internal static string MainWindow_Phase_LaunchPSO2 {
            get {
                return ResourceManager.GetString("MainWindow_Phase_LaunchPSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying mod files.
        /// </summary>
        internal static string MainWindow_Phase_ModFiles {
            get {
                return ResourceManager.GetString("MainWindow_Phase_ModFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to patch cache database.
        /// </summary>
        internal static string MainWindow_Phase_PatchCache {
            get {
                return ResourceManager.GetString("MainWindow_Phase_PatchCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading plugin info.
        /// </summary>
        internal static string MainWindow_Phase_PluginInfo {
            get {
                return ResourceManager.GetString("MainWindow_Phase_PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating PSO2 Directories.
        /// </summary>
        internal static string MainWindow_Phase_PSO2Directories {
            get {
                return ResourceManager.GetString("MainWindow_Phase_PSO2Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing PSO2 hook.
        /// </summary>
        internal static string MainWindow_Phase_PSO2h_TitleDisabled {
            get {
                return ResourceManager.GetString("MainWindow_Phase_PSO2h_TitleDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing PSO2 hook.
        /// </summary>
        internal static string MainWindow_Phase_PSO2h_TitleEnabled {
            get {
                return ResourceManager.GetString("MainWindow_Phase_PSO2h_TitleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Telepipe proxy.
        /// </summary>
        internal static string MainWindow_Phase_TelepipeProxy_TitleDisabled {
            get {
                return ResourceManager.GetString("MainWindow_Phase_TelepipeProxy_TitleDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Telepipe proxy.
        /// </summary>
        internal static string MainWindow_Phase_TelepipeProxy_TitleEnabled {
            get {
                return ResourceManager.GetString("MainWindow_Phase_TelepipeProxy_TitleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying files.
        /// </summary>
        internal static string MainWindow_Phase_VerifyFiles {
            get {
                return ResourceManager.GetString("MainWindow_Phase_VerifyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files verified of {1}.
        /// </summary>
        internal static string MainWindow_Phase_VerifyFiles_Message {
            get {
                return ResourceManager.GetString("MainWindow_Phase_VerifyFiles_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSO2 Options.
        /// </summary>
        internal static string MainWindow_PSO2Options {
            get {
                return ResourceManager.GetString("MainWindow_PSO2Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PSO2&apos;s graphics settings, including fullscreen mode and UI scale.
        /// </summary>
        internal static string MainWindow_PSO2OptionsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_PSO2OptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for PSO2 to exit.
        /// </summary>
        internal static string MainWindow_PSO2Running {
            get {
                return ResourceManager.GetString("MainWindow_PSO2Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT Extended Features.
        /// </summary>
        internal static string MainWindow_PSRTCheckbox {
            get {
                return ResourceManager.GetString("MainWindow_PSRTCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables PSRT Core—some tools may need this to function.
        /// </summary>
        internal static string MainWindow_PSRTCheckboxTooltip {
            get {
                return ResourceManager.GetString("MainWindow_PSRTCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes.
        /// </summary>
        internal static string MainWindow_ReleaseNotes {
            get {
                return ResourceManager.GetString("MainWindow_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset GameGuard.
        /// </summary>
        internal static string MainWindow_ResetGameGuard {
            get {
                return ResourceManager.GetString("MainWindow_ResetGameGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces GameGuard files to be redownloaded the next time you launch PSO2—may resolve GameGuard errors.
        /// </summary>
        internal static string MainWindow_ResetGameGuardTooltip {
            get {
                return ResourceManager.GetString("MainWindow_ResetGameGuardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telepipe Proxy (ARKS Layer).
        /// </summary>
        internal static string MainWindow_TelepipeCheckbox {
            get {
                return ResourceManager.GetString("MainWindow_TelepipeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads and enables ARKS Layer&apos;s translation tools—use this if PSO2 is blocked in your country.
        /// </summary>
        internal static string MainWindow_TelepipeCheckboxTooltip {
            get {
                return ResourceManager.GetString("MainWindow_TelepipeCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to download.
        /// </summary>
        internal static string MainWindow_UpdateAvailableDownload {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAvailableDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available!.
        /// </summary>
        internal static string MainWindow_UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update without launching.
        /// </summary>
        internal static string MainWindow_UpdateButton {
            get {
                return ResourceManager.GetString("MainWindow_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully update the game and apply patches.
        /// </summary>
        internal static string MainWindow_UpdateButtonTooltip {
            get {
                return ResourceManager.GetString("MainWindow_UpdateButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching update information.
        /// </summary>
        internal static string MainWindow_UpdateChecking {
            get {
                return ResourceManager.GetString("MainWindow_UpdateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch update information.
        /// </summary>
        internal static string MainWindow_UpdateError {
            get {
                return ResourceManager.GetString("MainWindow_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload error log.
        /// </summary>
        internal static string MainWindow_UploadErrorLogButton {
            get {
                return ResourceManager.GetString("MainWindow_UploadErrorLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify (File Check).
        /// </summary>
        internal static string MainWindow_VerifyFiles {
            get {
                return ResourceManager.GetString("MainWindow_VerifyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redownloads missing or corrupt game files—may resolve various game issues.
        /// </summary>
        internal static string MainWindow_VerifyFilesTooltip {
            get {
                return ResourceManager.GetString("MainWindow_VerifyFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PSO2 installation directory.
        /// </summary>
        internal static string OptionsWindow_ChangePSO2Directory {
            get {
                return ResourceManager.GetString("OptionsWindow_ChangePSO2Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Astra on launch.
        /// </summary>
        internal static string OptionsWindow_CloseOnLaunch {
            get {
                return ResourceManager.GetString("OptionsWindow_CloseOnLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Astra on a successful launch of the game..
        /// </summary>
        internal static string OptionsWindow_CloseOnLaunchTooltip {
            get {
                return ResourceManager.GetString("OptionsWindow_CloseOnLaunchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revalidate PSO2 Installation Cache.
        /// </summary>
        internal static string OptionsWindow_DeletePatchCache {
            get {
                return ResourceManager.GetString("OptionsWindow_DeletePatchCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch cache deleted.
        ///
        ///This file will start its regeneration upon your next attempt to launch PSO2 via PSRT Astra..
        /// </summary>
        internal static string OptionsWindow_DeletePatchCacheComplete {
            get {
                return ResourceManager.GetString("OptionsWindow_DeletePatchCacheComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT Astra uses a file caching algorithm to ensure your PSO2 installation is in a valid state each time you launch. This database is almost impossible to corrupt without manual tampering of the cache file.
        ///If you believe this to be corrupted, this option will delete this file and cause it to be regenerated using your current PSO2 installation.
        ///
        ///Be warned that this can take a long time as it requires scanning and validating of your entire PSO2 installation, it is the same operation that would have occurre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OptionsWindow_DeletePatchCacheConfirm {
            get {
                return ResourceManager.GetString("OptionsWindow_DeletePatchCacheConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Address Aware Patch.
        /// </summary>
        internal static string OptionsWindow_LargeAddressAware {
            get {
                return ResourceManager.GetString("OptionsWindow_LargeAddressAware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows PSO2 to assign itself more than 2GB RAM. Some users report this resolves crashes or texture corruption in certain situations..
        /// </summary>
        internal static string OptionsWindow_LargeAddressAwareTooltip {
            get {
                return ResourceManager.GetString("OptionsWindow_LargeAddressAwareTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telepipe Config Url.
        /// </summary>
        internal static string OptionsWindow_TelepipeProxyUrl {
            get {
                return ResourceManager.GetString("OptionsWindow_TelepipeProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override the proxy URL. Leave this blank to use Telepipe&apos;s default..
        /// </summary>
        internal static string OptionsWindow_TelepipeProxyUrlTooltip {
            get {
                return ResourceManager.GetString("OptionsWindow_TelepipeProxyUrlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsWindow_Title {
            get {
                return ResourceManager.GetString("OptionsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Current Application Log.
        /// </summary>
        internal static string OptionsWindow_UploadLog {
            get {
                return ResourceManager.GetString("OptionsWindow_UploadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Fullscreen.
        /// </summary>
        internal static string PSO2OptionsWindow_BorderlessFullscreen {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_BorderlessFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over an option for more information about its effects on your game..
        /// </summary>
        internal static string PSO2OptionsWindow_DefaultHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_DefaultHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard your changes?.
        /// </summary>
        internal static string PSO2OptionsWindow_DiscardChanges {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable DirectX 9Ex Features.
        /// </summary>
        internal static string PSO2OptionsWindow_EnableDirectX9Ex {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_EnableDirectX9Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets whether PSO2 will use newer DirectX features. Disabling this may fix graphics-related crashes on older systems, but will negatively impact performance and memory usage.
        ///
        ///If unsure, set this to Enabled..
        /// </summary>
        internal static string PSO2OptionsWindow_EnableDirectX9ExHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_EnableDirectX9ExHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Fullscreen.
        /// </summary>
        internal static string PSO2OptionsWindow_ExclusiveFullscreen {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_ExclusiveFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate Limit.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit120 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 144 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit144 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 240 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit240 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit30 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 FPS.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimit60 {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimit60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the maximum framerate PSO2 will run at. Setting this below your monitor&apos;s refresh rate (usually 60) will decrease visual smoothness, but may reduce hitching. Higher values will increase strain on your graphics card, but may make the game feel more responsive.
        ///
        ///If unsure, set this to 60 FPS..
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimitHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimitHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string PSO2OptionsWindow_FPSLimitUnlimited {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_FPSLimitUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Game Presets (Simple Render Setting).
        /// </summary>
        internal static string PSO2OptionsWindow_GraphicsPreset {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_GraphicsPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts your in-game graphics settings, overriding any changes. Higher values enable more eye-candy, but place more strain on your system. Some options may have no effect when Shader Quality is set to Low or Standard Quality..
        /// </summary>
        internal static string PSO2OptionsWindow_GraphicsPresetHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_GraphicsPresetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string PSO2OptionsWindow_Information {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_QualityHigh {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_QualityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_QualityLow {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_QualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_QualityStandard {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_QualityStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string PSO2OptionsWindow_Resolution {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets how many pixels the game renders each frame. This typically has the largest impact on performance and visual quality. Higher values place more strain on your graphics card. No effect when Window Mode is set to Borderless Fullscreen.
        ///
        ///If unsure, set this to your monitor&apos;s resolution..
        /// </summary>
        internal static string PSO2OptionsWindow_ResolutionHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_ResolutionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string PSO2OptionsWindow_SaveChanges {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_ShaderQuality {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_ShaderQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the quality of in-game lighting and effects. Higher quality places more strain on your graphics card. Some in-game options will have no effect on Low or Standard Quality..
        /// </summary>
        internal static string PSO2OptionsWindow_ShaderQualityHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_ShaderQualityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Quality.
        /// </summary>
        internal static string PSO2OptionsWindow_TextureQuality {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_TextureQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the resolution of in-game textures. Higher values will use sharper textures, but will also take up more graphics memory. This usually has negligible impact on performance, but a major impact on visual quality. Some low-end systems with weak or integrated graphics may need to lower this..
        /// </summary>
        internal static string PSO2OptionsWindow_TextureQualityHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_TextureQualityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Scale.
        /// </summary>
        internal static string PSO2OptionsWindow_UIScale {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.25x Scale.
        /// </summary>
        internal static string PSO2OptionsWindow_UIScale1Point25x {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScale1Point25x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5x Scale.
        /// </summary>
        internal static string PSO2OptionsWindow_UIScale1Point5x {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScale1Point5x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1x Scale.
        /// </summary>
        internal static string PSO2OptionsWindow_UIScale1x {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScale1x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the size of in-game interface elements, like your subpalette and HP bar. This option has no effect on performance..
        /// </summary>
        internal static string PSO2OptionsWindow_UIScaleHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_UIScaleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        internal static string PSO2OptionsWindow_Windowed {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_Windowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Mode.
        /// </summary>
        internal static string PSO2OptionsWindow_WindowMode {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_WindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets whether the game fills your screen. Borderless Fullscreen and Windowed allow you to switch applications quickly, but add a very small amount of display latency on some systems. Exclusive Fullscreen responds slightly faster, but switching applications is slower and may crash.
        ///
        ///If unsure, set this to Borderless Fullscreen..
        /// </summary>
        internal static string PSO2OptionsWindow_WindowModeHelp {
            get {
                return ResourceManager.GetString("PSO2OptionsWindow_WindowModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRT Astra.
        /// </summary>
        internal static string PSRTAstra {
            get {
                return ResourceManager.GetString("PSRTAstra", resourceCulture);
            }
        }
    }
}
